// Generated by build_final_codebook_data.py
// Authoritative metadata for all 50 limitation and non-limitation codes,
// with historical expansion diffs from the grounded iterative coding pipeline.

export interface CodeExpansion {
  version: '2020–2022' | '2023' | '2024' | '2025';
  addedClause: string;
}

export interface CodebookEntry {
  id: string;
  name: string;
  themeId: string;
  themeNumber: number;
  originVersion: 'Initial' | '2020–2022' | '2024' | '2025';
  paperCount: number;
  prevalencePct: number;
  definitionFull: string;
  definitionBase: string;
  expansions: CodeExpansion[];
  exampleQuote: string;
}

export interface MilestoneSummary {
  version: 'Initial' | '2020–2022' | '2023' | '2024' | '2025';
  label: string;
  iterationName: string;
  years: string;
  totalCodes: number;
  newCodesAdded: number;
  expandedCount: number;
  mergedCount: number;
  rejectedCount: number;
  clustersFormed: number;
  uniqueNewDetected: number;
  description: string;
}

export const MILESTONES: MilestoneSummary[] = [
  {
    version: 'Initial',
    label: 'C₀ Initial',
    iterationName: 'C₀ Initial Codebook',
    years: '2020 (Baseline)',
    totalCodes: 25,
    newCodesAdded: 25,
    expandedCount: 0,
    mergedCount: 0,
    rejectedCount: 0,
    clustersFormed: 25,
    uniqueNewDetected: 25,
    description: 'Initial deductive baseline of 25 codes (18 limitation codes + 7 non-limitation discourse codes) adapted from Xu et al. (2025) and literature.'
  },
  {
    version: '2020–2022',
    label: 'C₁ Iteration 1',
    iterationName: 'C₁ (2020–2022)',
    years: '2020–2022 Papers',
    totalCodes: 47,
    newCodesAdded: 22,
    expandedCount: 6,
    mergedCount: 75,
    rejectedCount: 0,
    clustersFormed: 105,
    uniqueNewDetected: 104,
    description: 'First inductive expansion round on 2020–2022 ACL/EMNLP papers. 104 new codes detected, clustered into 105 groups. Added 22 new codes (e.g., Bias/Fairness, Toxicity, Prompt Sensitivity, Deployment Barriers) and expanded definitions of 6 existing codes.'
  },
  {
    version: '2023',
    label: 'C₂ Iteration 2',
    iterationName: 'C₂ (2023)',
    years: '2023 Papers',
    totalCodes: 47,
    newCodesAdded: 0,
    expandedCount: 6,
    mergedCount: 95,
    rejectedCount: 0,
    clustersFormed: 104,
    uniqueNewDetected: 206,
    description: 'Empirical saturation reached: 0 new codes needed. 206 unique candidate codes consolidated into 104 clusters, with 95 merged into existing codes and 6 existing code definitions expanded (e.g., adding LLM-as-a-judge systematic biases to Reliance on Automatic Metrics).'
  },
  {
    version: '2024',
    label: 'C₃ Iteration 3',
    iterationName: 'C₃ (2024)',
    years: '2024 Papers',
    totalCodes: 48,
    newCodesAdded: 1,
    expandedCount: 4,
    mergedCount: 138,
    rejectedCount: 0,
    clustersFormed: 143,
    uniqueNewDetected: 200,
    description: 'Refined frontier behaviors. Added 1 new code (Literature Coverage Gap) and expanded 4 existing codes (including non-determinism in Model Reasoning Deficits and liability risks in Societal and Ethical Risks).'
  },
  {
    version: '2025',
    label: 'C₄ Iteration 4',
    iterationName: 'C₄ (2025)',
    years: '2025 Papers',
    totalCodes: 50,
    newCodesAdded: 2,
    expandedCount: 8,
    mergedCount: 64,
    rejectedCount: 0,
    clustersFormed: 74,
    uniqueNewDetected: 228,
    description: 'Final calibration on recent 2025 submissions. Added 2 granular codes (Sparse Data Sensitivity and Dataset Task Mismatch) and expanded 8 code definitions (e.g. context window limits in Scalability Bottleneck, watermark vulnerabilities in Privacy and Security Risks), achieving the final 50-code taxonomy.'
  }
];

export const CODEBOOK_ENTRIES: CodebookEntry[] = [
  {
    "id": "high-resource-requirements",
    "name": "High Resource Requirements",
    "themeId": "theme-1",
    "themeNumber": 1,
    "originVersion": "Initial",
    "paperCount": 3285,
    "prevalencePct": 20.47,
    "definitionFull": "Refers to the requirement for significant processing power, high-performance hardware (e.g., A100 GPUs, TPU pods), or excessive usage of memory (RAM, VRAM, or disk storage), which may prevent the model from being deployed on consumer-grade hardware or edge devices.",
    "definitionBase": "Refers to the requirement for significant processing power, high-performance hardware (e.g., A100 GPUs, TPU pods), or excessive usage of memory (RAM, VRAM, or disk storage), which may prevent the model from being deployed on consumer-grade hardware or edge devices.",
    "expansions": [],
    "exampleQuote": "Second, due to the limitation of computational resources, we focus on fine-tuning in this work, leaving applying ROSE to pre-training for future work."
  },
  {
    "id": "high-time-consumption",
    "name": "High Time Consumption",
    "themeId": "theme-1",
    "themeNumber": 1,
    "originVersion": "Initial",
    "paperCount": 1453,
    "prevalencePct": 9.05,
    "definitionFull": "Describes processes that require excessive duration for training, processing, or inference (latency), making the method unsuitable for some applications.",
    "definitionBase": "Describes processes that require excessive duration for training, processing, or inference (latency), making the method unsuitable for some applications.",
    "expansions": [],
    "exampleQuote": "Due to the complexity of the dynamic programming algorithm, it takes almost two days to finish all training epochs on 1 Tesla V100 GPU (32GB memory)."
  },
  {
    "id": "high-financial-cost",
    "name": "High Financial Cost",
    "themeId": "theme-1",
    "themeNumber": 1,
    "originVersion": "Initial",
    "paperCount": 1026,
    "prevalencePct": 6.39,
    "definitionFull": "Refers to prohibitive monetary expenses required to replicate or use the method, such as cloud computing fees, proprietary API costs, or paid datasets.",
    "definitionBase": "Refers to prohibitive monetary expenses required to replicate or use the method, such as cloud computing fees, proprietary API costs, or paid datasets.",
    "expansions": [],
    "exampleQuote": "First, due to budget limit, for the non-instruction following datasets, we only examined our methods with GPT3.5 and Gemini-1.0-Pro as LLM evaluators."
  },
  {
    "id": "human-labor-and-annotation-bottleneck",
    "name": "Human Labor and Annotation Bottleneck",
    "themeId": "theme-1",
    "themeNumber": 1,
    "originVersion": "2020\u20132022",
    "paperCount": 862,
    "prevalencePct": 5.37,
    "definitionFull": "A severe operational constraint where the method relies on heavy, non-scalable manual labor, domain expertise, or human intervention, or suffers from a scarcity, cognitive overload, or lack of quality control of human annotators.",
    "definitionBase": "A severe operational constraint where the method relies on heavy, non-scalable manual labor, domain expertise, or human intervention, or suffers from a scarcity, cognitive overload, or lack of quality control of human annotators.",
    "expansions": [],
    "exampleQuote": "Finally, our approach relies on human feedback on new questions that TeachMe fails to answer or fails to justify indicating significant human efforts."
  },
  {
    "id": "scalability-bottleneck",
    "name": "Scalability Bottleneck",
    "themeId": "theme-1",
    "themeNumber": 1,
    "originVersion": "2020\u20132022",
    "paperCount": 706,
    "prevalencePct": 4.4,
    "definitionFull": "An algorithmic and architectural limitation where the method experiences severe performance degradation, computational intractability, or exponential resource demands specifically as input lengths, dataset sizes, or model parameters grow. Includes static architectural constraints such as context window limitations or maximum input token lengths, which act as a hard ceiling for processing long-form data.",
    "definitionBase": "An algorithmic and architectural limitation where the method experiences severe performance degradation, computational intractability, or exponential resource demands specifically as input lengths, dataset sizes, or model parameters grow.",
    "expansions": [
      {
        "version": "2025",
        "addedClause": "Includes static architectural constraints such as context window limitations or maximum input token lengths, which act as a hard ceiling for processing long-form data."
      }
    ],
    "exampleQuote": "Second, our graph construction is quadratic in the number of document sentences, which restricts our method to documents of average length (e.g. 50-70 sentences)."
  },
  {
    "id": "high-data-requirement",
    "name": "High Data Requirement",
    "themeId": "theme-1",
    "themeNumber": 1,
    "originVersion": "2020\u20132022",
    "paperCount": 241,
    "prevalencePct": 1.5,
    "definitionFull": "Refers to architectural constraints where methods inherently demand massive volumes of training data to function competitively",
    "definitionBase": "Refers to architectural constraints where methods inherently demand massive volumes of training data to function competitively",
    "expansions": [],
    "exampleQuote": "One limitation of this work is that the generative model used in this paper requires a large amount of training data and is computationally expensive."
  },
  {
    "id": "environmental-impact",
    "name": "Environmental Impact",
    "themeId": "theme-1",
    "themeNumber": 1,
    "originVersion": "2020\u20132022",
    "paperCount": 106,
    "prevalencePct": 0.66,
    "definitionFull": "The real-world ecological consequences, such as carbon emissions and energy consumption, caused by the computational overhead of training or running large models.",
    "definitionBase": "The real-world ecological consequences, such as carbon emissions and energy consumption, caused by the computational overhead of training or running large models.",
    "expansions": [],
    "exampleQuote": "Thirdly, compared to single-agent approaches, multiple agents require more tokens and time, increasing computational demands and environmental impact."
  },
  {
    "id": "scope-limitation",
    "name": "Scope Limitation",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "Initial",
    "paperCount": 10091,
    "prevalencePct": 62.88,
    "definitionFull": "Clarifies the deliberate boundaries set by the researchers, detailing what was explicitly excluded from the study (e.g., specific languages, model sizes).",
    "definitionBase": "Clarifies the deliberate boundaries set by the researchers, detailing what was explicitly excluded from the study (e.g., specific languages, model sizes).",
    "expansions": [],
    "exampleQuote": "Despite the strong performance of our two key designs (COCO and iDRO), we mainly verify their efficacy from their empirical performance on BEIR tasks."
  },
  {
    "id": "methodological-constraints",
    "name": "Methodological Constraints",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "Initial",
    "paperCount": 6382,
    "prevalencePct": 39.77,
    "definitionFull": "Refers to fundamental restrictions embedded in the design, logic, or mathematical assumptions of the chosen method or architecture that cannot be easily fixed without changing the core approach. Includes: pipeline complexity, preprocessing overhead, training instability, hardware/framework incompatibilities, and the need for task-specific architectural adaptations.",
    "definitionBase": "Refers to fundamental restrictions embedded in the design, logic, or mathematical assumptions of the chosen method or architecture that cannot be easily fixed without changing the core approach.",
    "expansions": [
      {
        "version": "2020\u20132022",
        "addedClause": "Includes: pipeline complexity, preprocessing overhead, training instability, hardware/framework incompatibilities, and the need for task-specific architectural adaptations."
      }
    ],
    "exampleQuote": "We use a simple heuristically derived semantic similarity metric, which may not fully capture all aspects of semantic similarity between sentence pairs (Table 3)."
  },
  {
    "id": "generalization-gap",
    "name": "Generalization Gap",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "2020\u20132022",
    "paperCount": 2414,
    "prevalencePct": 15.04,
    "definitionFull": "A statistical and domain-transfer limitation where there is an empirical failure or uncertainty regarding a model's ability to maintain performance when transferred across different domains, languages, tasks, context lengths, modalities, cultural contexts, underlying model architectures, hardware platforms, or out-of-distribution datasets (e.g., zero-shot, long-tail, or out-of-vocabulary scenarios). Includes: vulnerability to overfitting on specific datasets or artifacts during training, and sensitivity to noisy, corrupted, or highly variable input data.",
    "definitionBase": "A statistical and domain-transfer limitation where there is an empirical failure or uncertainty regarding a model's ability to maintain performance when transferred across different domains, languages, tasks, context lengths, or out-of-distribution datasets (e.g., zero-shot, long-tail, or out-of-vocabulary scenarios).",
    "expansions": [
      {
        "version": "2023",
        "addedClause": "Includes: vulnerability to overfitting on specific datasets or artifacts during training, and sensitivity to noisy, corrupted, or highly variable input data."
      }
    ],
    "exampleQuote": "For the latter, we increase our dataset with samples from the CNN/DM dataset, partially mitigating the problem, but out-of-domain topics still suffer."
  },
  {
    "id": "empirical-underperformance",
    "name": "Empirical Underperformance",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "2020\u20132022",
    "paperCount": 1142,
    "prevalencePct": 7.12,
    "definitionFull": "A quantitative and comparative shortfall where the proposed method explicitly fails to match or exceed the measurable performance metrics of established baselines, state-of-the-art models, human experts, or theoretical upper bounds, or yields only marginal and underwhelming empirical improvements.",
    "definitionBase": "A quantitative and comparative shortfall where the proposed method explicitly fails to match or exceed the measurable performance metrics of established baselines, state-of-the-art models, human experts, or theoretical upper bounds.",
    "expansions": [
      {
        "version": "2023",
        "addedClause": ", or yields only marginal and underwhelming empirical improvements."
      }
    ],
    "exampleQuote": "First, there is still a performance gap between our method and the vanilla transformer in the language modeling task and CNN/Daily summarization task."
  },
  {
    "id": "real-world-deployment-barrier",
    "name": "Real-World Deployment Barrier",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "2020\u20132022",
    "paperCount": 1141,
    "prevalencePct": 7.11,
    "definitionFull": "An ecological validity and operational barrier where the fundamental assumptions, experimental setups, or structured workflows fail to represent the unstructured complexity, noise, and actual user behaviors present in live environments, rendering the method impractical for real-world deployment even if benchmark performance is high. Includes: evaluation datasets or synthetic data failing to faithfully capture the true distribution of live environments.",
    "definitionBase": "An ecological validity and operational barrier where the fundamental assumptions, experimental setups, or structured workflows fail to represent the unstructured complexity, noise, and actual user behaviors present in live environments, rendering the method impractical for real-world deployment even if benchmark performance is high.",
    "expansions": [
      {
        "version": "2025",
        "addedClause": "Includes: evaluation datasets or synthetic data failing to faithfully capture the true distribution of live environments."
      }
    ],
    "exampleQuote": "Moreover, our experiments are conducted on standard benchmark datasets, which may not faithfully represent the noise and complexity of real-world text streams."
  },
  {
    "id": "performance-trade-off",
    "name": "Performance Trade-off",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "Initial",
    "paperCount": 544,
    "prevalencePct": 3.39,
    "definitionFull": "Highlights scenarios where an improvement in one metric (e.g., efficiency, speed) results in a direct and unavoidable degradation of another metric (e.g., accuracy, quality).",
    "definitionBase": "Highlights scenarios where an improvement in one metric (e.g., efficiency, speed) results in a direct and unavoidable degradation of another metric (e.g., accuracy, quality).",
    "expansions": [],
    "exampleQuote": "Although the decrease of fluency is relatively small compared to"
  },
  {
    "id": "hyperparameter-sensitivity",
    "name": "Hyperparameter Sensitivity",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "2020\u20132022",
    "paperCount": 452,
    "prevalencePct": 2.82,
    "definitionFull": "A methodological and configuration fragility where a model's performance, stability, or success is highly contingent on precise architectural choices, random seed selection, or extensive manual tuning of mathematical hyperparameters, making the system difficult to optimize or reproduce without exhaustive trial and error.",
    "definitionBase": "A methodological and configuration fragility where a model's performance, stability, or success is highly contingent on precise architectural choices, random seed selection, or extensive manual tuning of mathematical hyperparameters, making the system difficult to optimize or reproduce without exhaustive trial and error.",
    "expansions": [],
    "exampleQuote": "Further, the need for extensive hyperparameter optimisation, particularly for combining loss functions, can hinder accessibility for non-expert users."
  },
  {
    "id": "temporal-degradation",
    "name": "Temporal Degradation",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "2020\u20132022",
    "paperCount": 373,
    "prevalencePct": 2.32,
    "definitionFull": "A vulnerability where a model's effectiveness degrades over time, or a dataset becomes obsolete, due to shifting language patterns, concept drift, or temporal cutoffs.",
    "definitionBase": "A vulnerability where a model's effectiveness degrades over time, or a dataset becomes obsolete, due to shifting language patterns, concept drift, or temporal cutoffs.",
    "expansions": [],
    "exampleQuote": "This can lead to a degraded real-world performance if a system relies exclusively on WebIE for evaluation when the dataset is not updated accordingly."
  },
  {
    "id": "prompt-sensitivity",
    "name": "Prompt Sensitivity",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "2020\u20132022",
    "paperCount": 325,
    "prevalencePct": 2.03,
    "definitionFull": "A linguistic and interaction fragility where a model's output quality, accuracy, or reasoning behavior fluctuates drastically based on minor variations in prompt wording, instructional phrasing, or formatting, demonstrating a lack of robustness to how a task is presented by the user. Includes: a strict dependency on high-quality, representative few-shot examples to function effectively.",
    "definitionBase": "A linguistic and interaction fragility where a model's output quality, accuracy, or reasoning behavior fluctuates drastically based on minor variations in prompt wording, instructional phrasing, or formatting, demonstrating a lack of robustness to how a task is presented by the user.",
    "expansions": [
      {
        "version": "2025",
        "addedClause": "Includes: a strict dependency on high-quality, representative few-shot examples to function effectively."
      }
    ],
    "exampleQuote": "We also note that using different prompt templates or changing the phrasing of instruction prompt leads to distinct response behaviors and performance (Table 5)."
  },
  {
    "id": "literature-coverage-gap",
    "name": "Literature Coverage Gap",
    "themeId": "theme-2",
    "themeNumber": 2,
    "originVersion": "2024",
    "paperCount": 92,
    "prevalencePct": 0.57,
    "definitionFull": "A methodological and scoping limitation where the authors explicitly acknowledge the potential omission of relevant prior works, recent findings, or valuable contributions due to the rapid expansion, vast volume, or dynamic nature of the scholarly literature in the field",
    "definitionBase": "A methodological and scoping limitation where the authors explicitly acknowledge the potential omission of relevant prior works, recent findings, or valuable contributions due to the rapid expansion, vast volume, or dynamic nature of the scholarly literature in the field",
    "expansions": [],
    "exampleQuote": "Although we attempted to review the literature comprehensively, the rapid growth of LLM research means some recent preprints might have been missed (Section 1)."
  },
  {
    "id": "dependency-on-upstream-quality",
    "name": "Dependency on Upstream Quality",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "Initial",
    "paperCount": 2549,
    "prevalencePct": 15.88,
    "definitionFull": "States that the method's performance is strictly bottlenecked by the quality of the underlying base model or preprocessing steps (errors flow downstream). Includes: structural domain mismatches between pre-training and downstream data, inheriting stylistic, structural, or content biases from upstream source data or simulators, and strict dependency on the characteristics of specific source data.",
    "definitionBase": "States that the method's performance is strictly bottlenecked by the quality of the underlying base model or preprocessing steps (errors flow downstream).",
    "expansions": [
      {
        "version": "2023",
        "addedClause": "Includes: structural domain mismatches between pre-training and downstream data, inheriting stylistic, structural, or content biases from upstream source data or simulators, and strict dependency on the characteristics of specific source data."
      }
    ],
    "exampleQuote": "Our model also suffers from the noisy OCR prediction of off-the-shelf object detector, whose performance will depend highly on the extracted OCR text qualities."
  },
  {
    "id": "data-scarcity",
    "name": "Data Scarcity",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "Initial",
    "paperCount": 2019,
    "prevalencePct": 12.58,
    "definitionFull": "Refers to the overall lack of sufficient data quantity, highlighting situations where there is very little data available or the data belongs to a niche domain, such as low-resource languages or tasks requiring rare examples. Includes: data collection attrition caused by low participant response rates or missing data.",
    "definitionBase": "Refers to the overall lack of sufficient data quantity, highlighting situations where there is very little data available or the data belongs to a niche domain, such as low-resource languages or tasks requiring rare examples.",
    "expansions": [
      {
        "version": "2025",
        "addedClause": "Includes: data collection attrition caused by low participant response rates or missing data."
      }
    ],
    "exampleQuote": "We clearly realize that our dataset size is relatively small compared with other related datasets due to its unique property of context-sensitiveness."
  },
  {
    "id": "dataset-bias-imbalance",
    "name": "Dataset Bias/Imbalance",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "Initial",
    "paperCount": 1615,
    "prevalencePct": 10.06,
    "definitionFull": "Acknowledges that the researchers did not have or collect enough data for certain groups, leading to a skewed data distribution, class imbalances, or misrepresentations that contain social/demographic biases (e.g., gender, race).",
    "definitionBase": "Acknowledges that the researchers did not have or collect enough data for certain groups, leading to a skewed data distribution, class imbalances, or misrepresentations that contain social/demographic biases (e.g., gender, race).",
    "expansions": [],
    "exampleQuote": "MTurk workers generally tend to be less religious, more educated, and more likely to be unemployed than the general population (Goodman et al., 2013)."
  },
  {
    "id": "low-data-quality",
    "name": "Low Data Quality",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "Initial",
    "paperCount": 1239,
    "prevalencePct": 7.72,
    "definitionFull": "Refers to low-quality data containing inaccuracies, typographical errors, wrong labels, formatting issues, or irrelevant content (\"garbage\") that confuses the model. Includes: dataset incompleteness, missing annotations or metadata, structural heterogeneity, lack of diversity, and the limitations of relying on unrepresentative synthetic or simulated data Includes: coarse labeling constraints lacking fine-grained granularity, inherent data ambiguity where categories lack clear semantic definitions, artifacts and semantic loss introduced by relying on machine translation",
    "definitionBase": "Refers to low-quality data containing inaccuracies, typographical errors, wrong labels, formatting issues, or irrelevant content (\"garbage\") that confuses the model.",
    "expansions": [
      {
        "version": "2020\u20132022",
        "addedClause": "Includes: dataset incompleteness, missing annotations or metadata, structural heterogeneity, lack of diversity, and the limitations of relying on unrepresentative synthetic or simulated data"
      },
      {
        "version": "2025",
        "addedClause": "Includes: coarse labeling constraints lacking fine-grained granularity, inherent data ambiguity where categories lack clear semantic definitions, artifacts and semantic loss introduced by relying on machine translation"
      }
    ],
    "exampleQuote": "For instance, OntoNotes 5.0 dataset contains 18 coarse-grained entity types while FEW-NERD contains 9 coarse-grained and 66 fine-grained entity types."
  },
  {
    "id": "reliance-on-external-tools-or-resources",
    "name": "Reliance on External Tools or Resources",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "Initial",
    "paperCount": 783,
    "prevalencePct": 4.88,
    "definitionFull": "Refers to the method's dependency on third-party software, APIs, parsers, or other models to function, which introduces risks of failure if those tools change or go offline. Includes: structural bottlenecks where performance is constrained by the limited coverage or availability of external knowledge bases.",
    "definitionBase": "Refers to the method's dependency on third-party software, APIs, parsers, or other models to function, which introduces risks of failure if those tools change or go offline.",
    "expansions": [
      {
        "version": "2020\u20132022",
        "addedClause": "Includes: structural bottlenecks where performance is constrained by the limited coverage or availability of external knowledge bases."
      }
    ],
    "exampleQuote": "Moreover, to automatically extract the expected evidence, we rely on core NLP tools such as coreference resolution, POS tagger and dependency parsers."
  },
  {
    "id": "resource-accessibility-barriers",
    "name": "Resource Accessibility Barriers",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "2020\u20132022",
    "paperCount": 590,
    "prevalencePct": 3.68,
    "definitionFull": "A systemic and infrastructural barrier where the broader community is restricted from accessing essential underlying materials due to proprietary data dependencies, closed-source models, copyright constraints, or financial obstacles (e.g., paywalled APIs), hindering the ability to build upon or extend the research.",
    "definitionBase": "A systemic and infrastructural barrier where the broader community is restricted from accessing essential underlying materials due to proprietary data dependencies, closed-source models, copyright constraints, or financial obstacles (e.g., paywalled APIs), hindering the ability to build upon or extend the research.",
    "expansions": [],
    "exampleQuote": "Further, many open and close language models are trained on content that cannot be acquired or redistributed, and thus could not be included in Dolma."
  },
  {
    "id": "dataset-task-mismatch",
    "name": "Dataset Task Mismatch",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "2025",
    "paperCount": 5,
    "prevalencePct": 0.03,
    "definitionFull": "A data-centric limitation where the available datasets used for training, fine-tuning, or evaluation do not structurally, semantically, or stylistically align with the target downstream task, specific domain, or intended real-world application.available resources",
    "definitionBase": "A data-centric limitation where the available datasets used for training, fine-tuning, or evaluation do not structurally, semantically, or stylistically align with the target downstream task, specific domain, or intended real-world application.available resources",
    "expansions": [],
    "exampleQuote": "Those that are available tend to use more general language than scientific medical writing; this is especially true for the En \u2192 Ar test set."
  },
  {
    "id": "sparse-data-sensitivity",
    "name": "Sparse Data Sensitivity",
    "themeId": "theme-3",
    "themeNumber": 3,
    "originVersion": "2025",
    "paperCount": 3,
    "prevalencePct": 0.02,
    "definitionFull": "data-centric limitation occurring at the inference or execution stage where the provided individual input data\u2014despite being valid and in-domain\u2014is too brief, fragmentary, or lacks sufficient contextual depth for the model to extract meaningful signals or perform accurate reasoning.",
    "definitionBase": "data-centric limitation occurring at the inference or execution stage where the provided individual input data\u2014despite being valid and in-domain\u2014is too brief, fragmentary, or lacks sufficient contextual depth for the model to extract meaningful signals or perform accurate reasoning.",
    "expansions": [],
    "exampleQuote": "Sparsity of Belief Signals Most users only post about a narrow subset of the belief topics we study, meaning their full belief structure is only partially observable."
  },
  {
    "id": "measurement-vulnerabilities",
    "name": "Measurement Vulnerabilities",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "2020\u20132022",
    "paperCount": 957,
    "prevalencePct": 5.96,
    "definitionFull": "Evaluation flaws where inconsistent experimental setups, lack of comparable baselines, hardware dependencies, missing ablation studies, or saturated benchmarks prevent a fair, comprehensive, and direct comparison with prior state-of-the-art work. Includes: high variance across different data splits, small evaluation scales preventing statistically robust conclusions, lack of expert validation, experimental design biases (e.g., ordering bias, outcome reporting, survivorship bias, or participant observation bias/Hawthorne effect), and proxy or surrogate model discrepancies.",
    "definitionBase": "Evaluation flaws where inconsistent experimental setups, lack of comparable baselines, hardware dependencies, missing ablation studies, or saturated benchmarks prevent a fair, comprehensive, and direct comparison with prior state-of-the-art work.",
    "expansions": [
      {
        "version": "2024",
        "addedClause": "Includes: high variance across different data splits, small evaluation scales preventing statistically robust conclusions, lack of expert validation, experimental design biases (e.g., ordering bias, outcome reporting, survivorship bias, or participant observation bias/Hawthorne effect), and proxy or surrogate model discrepancies."
      }
    ],
    "exampleQuote": "Although the random selection should ideally represent the whole distribution, the performance may vary slightly when comparing to the whole test set."
  },
  {
    "id": "subjectivity-in-evaluation-annotation",
    "name": "Subjectivity in Evaluation/Annotation",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "Initial",
    "paperCount": 840,
    "prevalencePct": 5.23,
    "definitionFull": "Refers to the inconsistency, bias, or lack of objectivity inherent in human annotations and assessments due to vague guidelines or personal interpretation. Includes: specific demographic biases introduced by a lack of demographic diversity among human annotators.",
    "definitionBase": "Refers to the inconsistency, bias, or lack of objectivity inherent in human annotations and assessments due to vague guidelines or personal interpretation.",
    "expansions": [
      {
        "version": "2023",
        "addedClause": "Includes: specific demographic biases introduced by a lack of demographic diversity among human annotators."
      }
    ],
    "exampleQuote": "While the benchmark dataset was annotated by human annotators, it is important to acknowledge the possibility of annotation errors or inconsistencies."
  },
  {
    "id": "theoretical-gap",
    "name": "Theoretical Gap",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "2020\u20132022",
    "paperCount": 694,
    "prevalencePct": 4.32,
    "definitionFull": "An analytical or epistemic limitation where the study identifies empirical success but lacks rigorous mathematical formalization, theoretical guarantees, or fails to isolate the underlying causal mechanisms and confounding variables driving the results.",
    "definitionBase": "An analytical or epistemic limitation where the study identifies empirical success but lacks rigorous mathematical formalization, theoretical guarantees, or fails to isolate the underlying causal mechanisms and confounding variables driving the results.",
    "expansions": [],
    "exampleQuote": "How to design a unified and more powerful KD method from the perspective of the connection between word- and sequence-level KD still remains unsolved."
  },
  {
    "id": "lack-of-reliable-evaluation-metrics-or-benchmarks",
    "name": "Lack of Reliable Evaluation Metrics or Benchmarks",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "Initial",
    "paperCount": 673,
    "prevalencePct": 4.19,
    "definitionFull": "Points out the absence of established standards, benchmarks, or effective mathematical formulas to measure a specific phenomenon accurately. Includes: structural vulnerabilities where chosen metrics are inadequate, inconsistent, or structurally fail to measure critical qualitative dimensions of model behavior",
    "definitionBase": "Points out the absence of established standards, benchmarks, or effective mathematical formulas to measure a specific phenomenon accurately.",
    "expansions": [
      {
        "version": "2020\u20132022",
        "addedClause": "Includes: structural vulnerabilities where chosen metrics are inadequate, inconsistent, or structurally fail to measure critical qualitative dimensions of model behavior"
      }
    ],
    "exampleQuote": "However, existing benchmarks for low-resource (Han et al., 2018; Gao et al., 2019) are limited to the simple scenario of sentence-level relation classification."
  },
  {
    "id": "reliance-on-automatic-metrics",
    "name": "Reliance on Automatic Metrics",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "Initial",
    "paperCount": 564,
    "prevalencePct": 3.51,
    "definitionFull": "Criticizes the dependence on algorithmic scoring systems (e.g., BLEU, ROUGE) which may not correlate with human judgment or semantic understanding. Includes: systematic biases introduced by using LLMs as automated evaluators (e.g., favoring their own generated text, preferring longer responses, or exhibiting instability and inconsistency across multiple evaluation runs).",
    "definitionBase": "Criticizes the dependence on algorithmic scoring systems (e.g., BLEU, ROUGE) which may not correlate with human judgment or semantic understanding.",
    "expansions": [
      {
        "version": "2024",
        "addedClause": "Includes: systematic biases introduced by using LLMs as automated evaluators (e.g., favoring their own generated text, preferring longer responses, or exhibiting instability and inconsistency across multiple evaluation runs)."
      }
    ],
    "exampleQuote": "Evaluation Metrics Second, we caveat that our accuracy metrics (STR-EM and Disambig-F1) only measure the recall of the required information in the long answers."
  },
  {
    "id": "data-leakage-contamination",
    "name": "Data Leakage/Contamination",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "Initial",
    "paperCount": 284,
    "prevalencePct": 1.77,
    "definitionFull": "Mentions the risk of evaluation data (test set) being inadvertently included or \"seen\" during the training phase, leading to invalid or inflated results.",
    "definitionBase": "Mentions the risk of evaluation data (test set) being inadvertently included or \"seen\" during the training phase, leading to invalid or inflated results.",
    "expansions": [],
    "exampleQuote": "Lastly, since training data for most models is not publicly available, data leakage from the training data corpus could possibly affects our findings."
  },
  {
    "id": "lack-of-interpretability",
    "name": "Lack of Interpretability",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "Initial",
    "paperCount": 278,
    "prevalencePct": 1.73,
    "definitionFull": "Refers to the difficulty in understanding the internal decision-making logic of the model, often described as the \"Black Box\" problem.",
    "definitionBase": "Refers to the difficulty in understanding the internal decision-making logic of the model, often described as the \"Black Box\" problem.",
    "expansions": [],
    "exampleQuote": "The black box nature of these models not only constrains our ability to comprehensively understand their behavior but also has ethical implications downstream."
  },
  {
    "id": "reproducibility-gap",
    "name": "Reproducibility Gap",
    "themeId": "theme-4",
    "themeNumber": 4,
    "originVersion": "2020\u20132022",
    "paperCount": 181,
    "prevalencePct": 1.13,
    "definitionFull": "A methodological and transparency barrier where the study lacks sufficient documentation, releases incomplete code, or omits crucial experimental configurations, preventing the broader research community from independently replicating the exact results or validating the original claims. Includes: the inability to accurately reproduce the results of external baselines due to unmaintained repositories or missing implementation details",
    "definitionBase": "A methodological and transparency barrier where the study lacks sufficient documentation, releases incomplete code, or omits crucial experimental configurations, preventing the broader research community from independently replicating the exact results or validating the original claims.",
    "expansions": [
      {
        "version": "2025",
        "addedClause": "Includes: the inability to accurately reproduce the results of external baselines due to unmaintained repositories or missing implementation details"
      }
    ],
    "exampleQuote": "We use proprietary LLMs like GPT-4 in certain experiments, and those results may be difficult reproduce if changes to the proprietary services occur."
  },
  {
    "id": "model-reasoning-and-generation-deficits",
    "name": "Model Reasoning and Generation Deficits",
    "themeId": "theme-5",
    "themeNumber": 5,
    "originVersion": "2020\u20132022",
    "paperCount": 673,
    "prevalencePct": 4.19,
    "definitionFull": "A behavioral and algorithmic limitation where the model exhibits flawed internal logic, fails to capture deep semantic meaning, relies on superficial or spurious cues, suffers from catastrophic forgetting, or produces generic, repetitive, and degenerate outputs. Includes: inherent behavioral instability or non-determinism across inference runs, and susceptibility to reward hacking.",
    "definitionBase": "A behavioral and algorithmic limitation where the model exhibits flawed internal logic, fails to capture deep semantic meaning, relies on superficial or spurious cues, suffers from catastrophic forgetting, or produces generic, repetitive, and degenerate outputs.",
    "expansions": [
      {
        "version": "2024",
        "addedClause": "Includes: inherent behavioral instability or non-determinism across inference runs, and susceptibility to reward hacking."
      }
    ],
    "exampleQuote": "As the appended adversarial suffix tokens may lack meaning, the resulting adversarial prompt found by the attack methods exhibits reduced naturalness."
  },
  {
    "id": "bias-and-fairness-risks",
    "name": "Bias and Fairness Risks",
    "themeId": "theme-5",
    "themeNumber": 5,
    "originVersion": "2020\u20132022",
    "paperCount": 453,
    "prevalencePct": 2.82,
    "definitionFull": "An ethical and socio-technical vulnerability where the system or dataset inherits, reproduces, or amplifies historical prejudices, cultural stereotypes, or exhibits structural disparities in performance across different demographic groups.",
    "definitionBase": "An ethical and socio-technical vulnerability where the system or dataset inherits, reproduces, or amplifies historical prejudices, cultural stereotypes, or exhibits structural disparities in performance across different demographic groups.",
    "expansions": [],
    "exampleQuote": "For convenience, this work uses a standard pronunciation acoustic model from MFA, which may disadvantage those with varying pronunciation preferences."
  },
  {
    "id": "model-hallucination-incoherence",
    "name": "Model Hallucination/Incoherence",
    "themeId": "theme-5",
    "themeNumber": 5,
    "originVersion": "Initial",
    "paperCount": 375,
    "prevalencePct": 2.34,
    "definitionFull": "Refers to the generation of output that is factually false, logically nonsensical, repetitive, or fluent but incorrect (common in LLMs).",
    "definitionBase": "Refers to the generation of output that is factually false, logically nonsensical, repetitive, or fluent but incorrect (common in LLMs).",
    "expansions": [],
    "exampleQuote": "At the same time, the generated premises could potentially contain fictional information, and should not be used for training models that learn facts from data."
  },
  {
    "id": "potential-for-misuse",
    "name": "Potential for Misuse",
    "themeId": "theme-5",
    "themeNumber": 5,
    "originVersion": "Initial",
    "paperCount": 246,
    "prevalencePct": 1.53,
    "definitionFull": "Emphasizes the ethical risks where the technology could be exploited for malicious purposes, fraud, disinformation, or harmful content generation.",
    "definitionBase": "Emphasizes the ethical risks where the technology could be exploited for malicious purposes, fraud, disinformation, or harmful content generation.",
    "expansions": [],
    "exampleQuote": "For instance, systems might exploit inferred emotional or cognitive states to influence decisions in commercial, political, or interpersonal contexts."
  },
  {
    "id": "societal-and-ethical-risks",
    "name": "Societal and Ethical Risks",
    "themeId": "theme-5",
    "themeNumber": 5,
    "originVersion": "2020\u20132022",
    "paperCount": 228,
    "prevalencePct": 1.42,
    "definitionFull": "The unintended real-world harms caused by the deployment of a technology, including legal and liability risks, negative downstream societal impacts, automation bias, deceptive persuasion, and ethical or labor concerns regarding the exploitation of human annotators.",
    "definitionBase": "The unintended real-world harms caused by the deployment of a technology, including negative downstream societal impacts, automation bias, deceptive persuasion, and ethical or labor concerns regarding the exploitation of human annotators.",
    "expansions": [
      {
        "version": "2024",
        "addedClause": "legal and liability risks,"
      }
    ],
    "exampleQuote": "However, the current model outputs may be factually inconsistent with the input documents, and in such a case could contribute to misinformation on the internet."
  },
  {
    "id": "privacy-and-security-risks",
    "name": "Privacy and Security Risks",
    "themeId": "theme-5",
    "themeNumber": 5,
    "originVersion": "2020\u20132022",
    "paperCount": 192,
    "prevalencePct": 1.2,
    "definitionFull": "An ethical and security vulnerability where the system or dataset could inadvertently expose sensitive personal information, user feedback, or be susceptible to adversarial attacks. Includes: vulnerabilities in watermarks, defense mechanisms, paraphrasing attacks, or countermeasures.",
    "definitionBase": "An ethical and security vulnerability where the system or dataset could inadvertently expose sensitive personal information, user feedback, or be susceptible to adversarial attacks.",
    "expansions": [
      {
        "version": "2025",
        "addedClause": "Includes: vulnerabilities in watermarks, defense mechanisms, paraphrasing attacks, or countermeasures."
      }
    ],
    "exampleQuote": "A concept has the potential to reveal additional information about the input, which may not be immediately evident upon inspecting the concept itself."
  },
  {
    "id": "toxicity-risks",
    "name": "Toxicity Risks",
    "themeId": "theme-5",
    "themeNumber": 5,
    "originVersion": "2020\u20132022",
    "paperCount": 128,
    "prevalencePct": 0.8,
    "definitionFull": "A behavioral and content-safety vulnerability where the system could inadvertently generate or be provoked into producing abusive language, hate speech, or other violent, offensive, and inappropriate content.",
    "definitionBase": "A behavioral and content-safety vulnerability where the system could inadvertently generate or be provoked into producing abusive language, hate speech, or other violent, offensive, and inappropriate content.",
    "expansions": [],
    "exampleQuote": "Moreover, the training datasets we used contain violence, abuse, and biased content that can be upsetting or offensive to particular groups of people."
  },
  {
    "id": "non-limitation-future-work",
    "name": "Non-Limitation: Future Work",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "Initial",
    "paperCount": 12041,
    "prevalencePct": 75.04,
    "definitionFull": "Suggests potential improvements or delegates specific unaddressed features, unanswered questions, or planned extensions to be explored in subsequent studies. Includes: theoretical mitigations proposed by the authors.",
    "definitionBase": "Suggests potential improvements or delegates specific unaddressed features, unanswered questions, or planned extensions to be explored in subsequent studies.",
    "expansions": [
      {
        "version": "2020\u20132022",
        "addedClause": "Includes: theoretical mitigations proposed by the authors."
      }
    ],
    "exampleQuote": "There are also ways to incorporate model generated labelling methods for more robust semi-supervision into our framework that we leave to future work."
  },
  {
    "id": "non-limitation-contextual-justification",
    "name": "Non-Limitation: Contextual Justification",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "Initial",
    "paperCount": 6561,
    "prevalencePct": 40.89,
    "definitionFull": "Refers to explanations that provide external background, common field practices, or real-world constraints to defend and justify a limitation.",
    "definitionBase": "Refers to explanations that provide external background, common field practices, or real-world constraints to defend and justify a limitation.",
    "expansions": [],
    "exampleQuote": "This is largely due to copyright issues involved with using more modern texts, and because of this, our models are inherently biased to the language used in older texts."
  },
  {
    "id": "non-limitation-method-details",
    "name": "Non-Limitation: Method Details",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "Initial",
    "paperCount": 5016,
    "prevalencePct": 31.26,
    "definitionFull": "Refers to factual descriptions of the proposed method which are typically stated to explain the root cause of a specific limitation.",
    "definitionBase": "Refers to factual descriptions of the proposed method which are typically stated to explain the root cause of a specific limitation.",
    "expansions": [],
    "exampleQuote": "Intuitively, the connection between nodes in the input graph can influence the encoding of x by guiding what to extract from x in order to generate y."
  },
  {
    "id": "non-limitation-strong-reported-performance",
    "name": "Non-Limitation: Strong Reported Performance",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "Initial",
    "paperCount": 4668,
    "prevalencePct": 29.09,
    "definitionFull": "Refers to statements explicitly highlighting the model's empirical success, effectiveness, or superior benchmark results.",
    "definitionBase": "Refers to statements explicitly highlighting the model's empirical success, effectiveness, or superior benchmark results.",
    "expansions": [],
    "exampleQuote": "Although MABEL shows exciting performance across an extensive range of evaluation settings, these results should not be construed as a complete erasure of bias."
  },
  {
    "id": "non-limitation-theoretical-projection",
    "name": "Non-Limitation: Theoretical Projection",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "2020\u20132022",
    "paperCount": 2600,
    "prevalencePct": 16.2,
    "definitionFull": "Optimistic or theoretical guesses, as well as explicit uncertainties, regarding how a method might perform in untested scenarios, unseen domains, or with future parameter and scale adjustments.",
    "definitionBase": "Optimistic or theoretical guesses, as well as explicit uncertainties, regarding how a method might perform in untested scenarios, unseen domains, or with future parameter and scale adjustments.",
    "expansions": [],
    "exampleQuote": "We expect improvements in classification performance when applied to multiclass or multilabel classification settings, but we have not confirmed this."
  },
  {
    "id": "non-limitation-conducted-mitigation",
    "name": "Non-Limitation: Conducted Mitigation",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "Initial",
    "paperCount": 2366,
    "prevalencePct": 14.74,
    "definitionFull": "Describes proactive steps, alternative methods, or workarounds that the researchers have already implemented within the study to alleviate a limitation. Includes: failed mitigation attempts.",
    "definitionBase": "Describes proactive steps, alternative methods, or workarounds that the researchers have already implemented within the study to alleviate a limitation.",
    "expansions": [
      {
        "version": "2020\u20132022",
        "addedClause": "Includes: failed mitigation attempts."
      }
    ],
    "exampleQuote": "To reduce the impact of LM bias, we generate hundreds of thousands of test cases to increase the chance we obtain test cases for a given sub-category."
  },
  {
    "id": "non-limitation-method-strength",
    "name": "Non-Limitation: Method Strength",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "Initial",
    "paperCount": 2021,
    "prevalencePct": 12.59,
    "definitionFull": "Highlights the theoretical, structural, or conceptual advantages of the proposed approach, distinct from empirical performance.",
    "definitionBase": "Highlights the theoretical, structural, or conceptual advantages of the proposed approach, distinct from empirical performance.",
    "expansions": [],
    "exampleQuote": "In this work, we propose a method to draw structured robust early-bird tickets, which can be used as an efficient alternative to adversarial training."
  },
  {
    "id": "non-limitation-anticipated-impact",
    "name": "Non-Limitation: Anticipated Impact",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "Initial",
    "paperCount": 1508,
    "prevalencePct": 9.4,
    "definitionFull": "Expresses the authors' hopes, expectations, or the broader potential influence that their findings might have on the research community or industry.",
    "definitionBase": "Expresses the authors' hopes, expectations, or the broader potential influence that their findings might have on the research community or industry.",
    "expansions": [],
    "exampleQuote": "We hope our findings can inform potential avenues of improvement on data augmentation for NER and"
  },
  {
    "id": "non-limitation-recommendations",
    "name": "Non-Limitation: Recommendations",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "2020\u20132022",
    "paperCount": 1106,
    "prevalencePct": 6.89,
    "definitionFull": "Outward-facing directives advising the broader research or practitioner community to adopt specific operational practices, metrics, strategies, or to contribute to specific research directions.",
    "definitionBase": "Outward-facing directives advising the broader research or practitioner community to adopt specific operational practices, metrics, strategies, or to contribute to specific research directions.",
    "expansions": [],
    "exampleQuote": "In the long-run, the community should build more elaborate coherence measures, to build a more complete picture of model capabilities and limitations."
  },
  {
    "id": "non-limitation-authorial-disclaimers",
    "name": "Non-Limitation: Authorial Disclaimers",
    "themeId": "non-limitation",
    "themeNumber": 0,
    "originVersion": "2020\u20132022",
    "paperCount": 839,
    "prevalencePct": 5.23,
    "definitionFull": "Explicit epistemic boundaries and warnings drawn by authors to prevent readers from overclaiming, misinterpreting, or prematurely deploying the empirical results in real-world or high-stakes applications.",
    "definitionBase": "Explicit epistemic boundaries and warnings drawn by authors to prevent readers from overclaiming, misinterpreting, or prematurely deploying the empirical results in real-world or high-stakes applications.",
    "expansions": [],
    "exampleQuote": "Regardless, we believe our models should be utilized with caution and approaches to mitigating social risks, biases, and toxicities should be carefully applied."
  }
];

export function getCodebookEntryByName(name: string): CodebookEntry | undefined {
  return CODEBOOK_ENTRIES.find((c) => c.name.toLowerCase() === name.toLowerCase());
}

export function getCodebookEntryById(id: string): CodebookEntry | undefined {
  return CODEBOOK_ENTRIES.find((c) => c.id === id);
}

export function getCodebookEntriesByTheme(themeId: string): CodebookEntry[] {
  return CODEBOOK_ENTRIES.filter((c) => c.themeId === themeId);
}
